apiVersion: apps/v1
kind: Deployment
metadata:
  name: fightbooker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fightbooker
  template:
    metadata:
      labels:
        app: fightbooker
    spec:
      containers:
        - image: softwarequality/flightbooker
          name: fightbooker
          ports:
            - containerPort: 8080
              name: fightbooker